<?php

return [
    'name' => env('PORTFOLIO_NAME', 'Ari Eka Putragani'),
    'role' => env('PORTFOLIO_ROLE', 'Full-Stack Web Developer'),
    'title' => env('PORTFOLIO_TITLE', 'Portofolio — Ari Eka Putragani'),
    'description' => 'Portofolio pribadi: proyek, artikel, dan layanan pengembangan web.',
    'url' => env('APP_URL', 'http://localhost'),
    'email' => env('PORTFOLIO_EMAIL', 'email@example.com'),
    'location' => env('PORTFOLIO_LOCATION', 'Jakarta, Indonesia'),
    'hero' => [
        'greeting' => 'Halo, saya',
        'intro' => 'Saya membangun pengalaman web yang cepat, modern, dan mudah digunakan — mulai dari landing page hingga aplikasi kompleks.',
        'tech' => ['Laravel', 'PHP', 'JavaScript', 'Bootstrap', 'Next.js'],
    ],
    'socials' => [
        'github' => env('PORTFOLIO_GITHUB', 'https://github.com/username'),
        'linkedin' => env('PORTFOLIO_LINKEDIN', 'https://linkedin.com/in/username'),
        'twitter' => env('PORTFOLIO_TWITTER', 'https://twitter.com/username'),
        'instagram' => env('PORTFOLIO_INSTAGRAM', 'https://instagram.com/username'),
    ],
    'nav' => [
        ['label' => 'Beranda', 'href' => '/'],
        ['label' => 'Tentang', 'href' => '/tentang'],
        ['label' => 'Proyek', 'href' => '/proyek'],
        ['label' => 'Layanan', 'href' => '/layanan'],
        ['label' => 'Blog', 'href' => '/blog'],
        ['label' => 'Kontak', 'href' => '/kontak'],
    ],
    'highlights' => [
        'Pengalaman 3+ tahun di bidang pengembangan web',
        'Menguasai Laravel, PHP, dan ekosistem JavaScript',
        'Fokus pada performa, SEO, dan aksesibilitas',
        'Terbiasa bekerja dengan tim maupun secara mandiri',
    ],
    'skills' => [
        ['name' => 'Laravel / PHP', 'level' => 92],
        ['name' => 'JavaScript (ES6+)', 'level' => 88],
        ['name' => 'Bootstrap / CSS', 'level' => 85],
        ['name' => 'Node.js / API', 'level' => 78],
    ],
    'services' => [
        [
            'slug' => 'web-development',
            'title' => 'Pengembangan Website',
            'icon' => 'fa-solid fa-code',
            'description' => 'Membangun website modern, cepat, dan responsif menggunakan Laravel dan PHP dengan standar kode yang rapi dan mudah dikelola.',
            'points' => [
                'Website company profile & landing page',
                'Web aplikasi interaktif',
                'Optimasi kecepatan & performa',
                'Responsive untuk semua perangkat',
            ],
        ],
        [
            'slug' => 'ui-design',
            'title' => 'UI/UX Design',
            'icon' => 'fa-solid fa-palette',
            'description' => 'Merancang antarmuka yang menarik dan pengalaman pengguna yang intuitif, dari wireframe hingga desain akhir siap implementasi.',
            'points' => [
                'Wireframe & prototype',
                'Design system & komponen',
                'Dark mode & theming',
                'Audit usability',
            ],
        ],
        [
            'slug' => 'cms-integration',
            'title' => 'CMS & Integrasi',
            'icon' => 'fa-solid fa-database',
            'description' => 'Mengintegrasikan content management system dan layanan pihak ketiga agar konten mudah dikelola tanpa perlu koding.',
            'points' => [
                'Headless CMS (Sanity, Contentful)',
                'Integrasi payment gateway',
                'Autentikasi & API',
                'Migrasi data',
            ],
        ],
        [
            'slug' => 'seo-optimization',
            'title' => 'Optimasi SEO',
            'icon' => 'fa-solid fa-magnifying-glass',
            'description' => 'Meningkatkan visibilitas website di mesin pencari melalui teknik on-page SEO, structured data, dan technical SEO.',
            'points' => [
                'Audit & strategi SEO',
                'Metadata & Open Graph',
                'Sitemap & robots.txt',
                'Structured data (JSON-LD)',
            ],
        ],
    ],
    'technologies' => [
        'Language' => [
            ['name' => 'HTML', 'level' => 'Expert'],
            ['name' => 'CSS', 'level' => 'Expert'],
            ['name' => 'JavaScript', 'level' => 'Expert'],
            ['name' => 'PHP', 'level' => 'Expert'],
            ['name' => 'Java', 'level' => 'Advanced'],
            ['name' => 'C++', 'level' => 'Intermediate'],
            ['name' => 'Dart', 'level' => 'Advanced'],
            ['name' => 'Python', 'level' => 'Advanced'],
            ['name' => 'SQL', 'level' => 'Expert'],
            ['name' => 'Kotlin', 'level' => 'Intermediate'],
            ['name' => 'Golang', 'level' => 'Intermediate'],
            ['name' => 'Sass', 'level' => 'Advanced'],
        ],
        'Framework' => [
            ['name' => 'Laravel', 'level' => 'Expert'],
            ['name' => 'Next.js', 'level' => 'Expert'],
            ['name' => 'React', 'level' => 'Expert'],
            ['name' => 'Vue.js', 'level' => 'Expert'],
            ['name' => 'Flask', 'level' => 'Advanced'],
            ['name' => 'Express.js', 'level' => 'Advanced'],
            ['name' => 'Spring Boot', 'level' => 'Intermediate'],
            ['name' => 'CodeIgniter', 'level' => 'Advanced'],
            ['name' => 'Lumen', 'level' => 'Advanced'],
        ],
        'Library' => [
            ['name' => 'Bootstrap', 'level' => 'Expert'],
            ['name' => 'Material UI', 'level' => 'Advanced'],
            ['name' => 'Chart.js', 'level' => 'Advanced'],
            ['name' => 'Axios', 'level' => 'Expert'],
            ['name' => 'jQuery', 'level' => 'Expert'],
            ['name' => 'NumPy', 'level' => 'Intermediate'],
            ['name' => 'Pandas', 'level' => 'Intermediate'],
            ['name' => 'Scikit-learn', 'level' => 'Intermediate'],
        ],
        'DBMS' => [
            ['name' => 'MySQL', 'level' => 'Expert'],
            ['name' => 'PostgreSQL', 'level' => 'Expert'],
            ['name' => 'MongoDB', 'level' => 'Advanced'],
            ['name' => 'Oracle', 'level' => 'Intermediate'],
            ['name' => 'SQL Server', 'level' => 'Advanced'],
        ],
        'Tools' => [
            ['name' => 'Git', 'level' => 'Expert'],
            ['name' => 'Docker', 'level' => 'Advanced'],
            ['name' => 'VSCode', 'level' => 'Expert'],
            ['name' => 'Postman', 'level' => 'Expert'],
            ['name' => 'Figma', 'level' => 'Advanced'],
        ],
    ],
    'translations' => [
        'en' => [
            'nav.beranda' => 'Home',
            'nav.tentang' => 'About',
            'nav.proyek' => 'Projects',
            'nav.layanan' => 'Services',
            'nav.blog' => 'Blog',
            'nav.kontak' => 'Contact',
            'nav.hubungi' => 'Contact Me',
            'nav.login' => 'Login',
            'hero.halo' => 'Hello, I am',
            'hero.role' => 'Full-Stack Web Developer',
            'hero.intro' => 'I build fast, modern, and easy-to-use web experiences — from landing pages to complex applications.',
            'hero.cta_proyek' => 'View Projects',
            'hero.cta_kontak' => 'Contact Me',
            'carousel.proyek' => 'My Projects',
            'carousel.subtitle' => 'A selection of projects I have built.',
            'about.eyebrow' => 'About Me',
            'about.title_1' => 'Building digital solutions that make an',
            'about.title_2' => 'impact',
            'about.text' => 'I am a Full-Stack Web Developer who loves turning ideas into real digital products. From designing architecture to interaction details, I strive to deliver the best quality in every project.',
            'about.cta' => 'Learn More',
            'about.skills' => 'Skills',
            'layanan.eyebrow' => 'Services',
            'layanan.title' => 'What I offer',
            'layanan.subtitle' => 'Complementary services to support your digital needs.',
            'layanan.cta' => 'All Services',
            'blog.eyebrow' => 'Latest Articles',
            'blog.title' => 'Blog',
            'blog.subtitle' => 'Articles about web development, SEO, and technology.',
            'blog.cta' => 'All Posts',
            'kontak.eyebrow' => 'Contact',
            'kontak.title' => 'Get in touch',
            'kontak.subtitle' => 'Ready to start a project? Send me a message.',
            'kontak.form' => 'Send Message',
            'kontak.alamat' => 'Address',
            'kontak.email' => 'Email',
            'kontak.telepon' => 'Phone',
            'kontak.nama' => 'Name',
            'kontak.phone_label' => 'Phone Number',
            'kontak.pesan' => 'Message',
            'kontak.kirim' => 'Send',
            'footer.tagline' => 'Personal portfolio: projects, articles, and web development services.',
            'footer.navigasi' => 'Navigation',
            'footer.kontak' => 'Contact',
            'footer.dibuat' => 'Built with Laravel & Bootstrap.',
            'proyek.eyebrow' => 'Portfolio',
            'proyek.title' => 'My Projects',
            'proyek.subtitle' => 'A selection of projects I have worked on.',
            'proyek.detail' => 'Detail',
            'proyek.semua' => 'All Projects',
            'proyek.stack' => 'Stack',
            'proyek.fitur' => 'Features',
            'proyek.kembali' => 'Back to projects',
            'proyek.demo' => 'Live Demo',
            'proyek.github' => 'Source Code',
            'blog.artikel' => 'Posts',
            'blog.semua' => 'All Posts',
            'blog.baca' => 'Read More',
            'blog.dibaca' => 'min read',
            'tech.title_1' => 'Tech',
            'tech.title_2' => 'Pipeline',
            'tech.active' => 'Active',
            'tech.flowing' => 'Technologies Flowing',
            'tech.loop' => 'Infinite Loop',
            'tech.pipelines' => 'Active Pipelines',
        ],
    ],
];