<?php

return [
    [
        'slug' => 'ecommerce-app',
        'title' => 'Aplikasi E-Commerce',
        'subtitle' => 'Toko online lengkap dengan keranjang & pembayaran',
        'description' => 'Aplikasi e-commerce full-stack dengan katalog produk, keranjang belanja, checkout, dan integrasi payment gateway. Dilengkapi dashboard admin untuk mengelola produk dan pesanan.',
        'image' => '/images/projects/ecommerce.svg',
        'stack' => ['Next.js', 'PostgreSQL', 'Prisma', 'Tailwind CSS'],
        'github' => 'https://github.com/username/ecommerce-app',
        'live' => 'https://ecommerce-demo.vercel.app',
        'featured' => true,
        'year' => '2025',
        'features' => [
            'Autentikasi & otorisasi pengguna',
            'Keranjang belanja real-time',
            'Integrasi payment gateway',
            'Dashboard admin produk & pesanan',
            'Optimasi performa & SEO',
        ],
    ],
    [
        'slug' => 'crm-dashboard',
        'title' => 'CRM Dashboard',
        'subtitle' => 'Panel analitik untuk tim sales',
        'description' => 'Dashboard CRM untuk mengelola customer, pipeline penjualan, dan laporan performa tim. Dilengkapi visualisasi data interaktif dan fitur ekspor laporan.',
        'image' => '/images/projects/crm.svg',
        'stack' => ['React', 'TypeScript', 'Recharts', 'Node.js'],
        'github' => 'https://github.com/username/crm-dashboard',
        'live' => null,
        'featured' => true,
        'year' => '2024',
        'features' => [
            'Manajemen customer & pipeline',
            'Grafik performa interaktif',
            'Laporan harian/bulanan',
            'Filter & pencarian lanjutan',
            'Mode gelap',
        ],
    ],
    [
        'slug' => 'portfolio-theme',
        'title' => 'Tema Portofolio',
        'subtitle' => 'Template portofolio modern & responsif',
        'description' => 'Template portofolio open-source dengan animasi halus, dark mode, dan optimasi SEO. Dibangun dengan fokus pada kecepatan dan aksesibilitas.',
        'image' => '/images/projects/portfolio.svg',
        'stack' => ['Next.js', 'Bootstrap', 'Framer Motion'],
        'github' => 'https://github.com/username/portfolio-theme',
        'live' => 'https://portfolio-theme.vercel.app',
        'featured' => false,
        'year' => '2025',
        'features' => [
            'Desain responsif mobile-first',
            'Dark mode dengan toggle',
            'Animasi scroll menggunakan Framer Motion',
            'SEO lengkap (OG, sitemap, robots)',
            'Gratis & open source',
        ],
    ],
    [
        'slug' => 'weather-app',
        'title' => 'Aplikasi Cuaca',
        'subtitle' => 'Prakiraan cuaca real-time berbasis lokasi',
        'description' => 'Aplikasi cuaca yang menampilkan prakiraan harian dan mingguan berdasarkan lokasi pengguna, dengan visual ikon yang dinamis dan data dari API cuaca publik.',
        'image' => '/images/projects/weather.svg',
        'stack' => ['React', 'REST API', 'CSS Modules'],
        'github' => 'https://github.com/username/weather-app',
        'live' => null,
        'featured' => false,
        'year' => '2024',
        'features' => [
            'Deteksi lokasi otomatis',
            'Prakiraan 7 hari ke depan',
            'Visual ikon cuaca dinamis',
            'Unit suhu Celsius/Fahrenheit',
        ],
    ],
];